# -*- coding: utf-8 -*-
"""EST_SafeLink.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PuxE7Ld8IjuOEzzQCtgK_nwybxl7mPk

### 1. 라이브러리 임포트
필요한 라이브러리들을 불러옵니다. TIF 파일을 다루기 위해 `rasterio`를 사용할 수 있으며, 머신러닝 모델을 위해 `scikit-learn`과 모델 저장을 위한 `joblib`을 사용합니다.
"""

from google.colab import drive
drive.mount('/content/drive')

# ==========================================
# 📂 파일 경로 설정
# ==========================================
csv_path = '/content/drive/MyDrive/Colab Notebooks/EST AI Challengers/해커톤/산림청_최근 5년간 전국 산사태 발생 이력_20250101.csv'
tif1_path = '/content/drive/MyDrive/Colab Notebooks/EST AI Challengers/해커톤/산사태 위험지도/11.tif' # 서울 (검증용)
# tif2_path = '/content/drive/MyDrive/Colab Notebooks/EST AI Challengers/해커톤/산사태 위험지도/41.tif' # 경기
tif3_path = '/content/drive/MyDrive/Colab Notebooks/EST AI Challengers/해커톤/산사태 위험지도/51.tif' # 강원 (학습용)
kma_api_key_path = '/content/drive/MyDrive/Colab Notebooks/EST AI Challengers/해커톤/기상청api.txt'
dem_path = '/content/drive/MyDrive/Colab Notebooks/EST AI Challengers/해커톤/한반도90m_GRS80.img'

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import joblib
# import rasterio

"""### API 데이터 구조 확인
아래 코드는 API의 실제 주소와 파라미터(인증키 등)를 입력했을 때, 응답 데이터의 구조를 파악하기 위한 헬퍼 함수입니다. 실제 URL을 넣고 실행한 뒤 결과를 확인해보세요.
"""

import requests
import pandas as pd
import io

def fetch_kma_data(url, params=None):
    try:
        print(f"요청 중: {url.split('?')[0]}...")
        response = requests.get(url, params=params)
        response.raise_for_status() # HTTP 에러 발생 시 예외 처리

        # 기상청 데이터는 JSON이 아닌 텍스트 형식입니다.
        text_data = response.text

        # 줄바꿈 기준으로 데이터를 나눔
        lines = text_data.split('\n')

        # '#'으로 시작하는 주석 라인과 'TM'으로 시작하는 요약 라인, 빈 라인 제거
        data_lines = [line.strip() for line in lines if not line.startswith('#') and not line.startswith('TM') and line.strip()]

        # DataFrame으로 변환 (tm, ta, td, hm 컬럼 기준)
        csv_data = '\n'.join(data_lines)
        df = pd.read_csv(io.StringIO(csv_data), names=['tm', 'ta', 'td', 'hm'])

        print("\n--- 기상청 데이터 파싱 완료 ---")
        return df

    except Exception as e:
        print(f"데이터를 불러오는 중 오류가 발생했습니다: {e}")
        return None

# ==========================================
# 기상청 API 데이터 불러오기 (상단 변수 kma_api_key_path 활용)
# ==========================================

try:
    with open(kma_api_key_path, 'r', encoding='utf-8') as f:
        kma_auth_key = f.read().strip()
except Exception as e:
    print(f"API 키 파일을 읽는 중 오류 발생: {e}")
    kma_auth_key = ""

# 위도(lat)=37.57141, 경도(lon)=126.96579는 서울 지역입니다.
weather_url = "https://apihub.kma.go.kr/api/typ01/url/sfc_nc_var.php?tm1=202606110000&tm2=202606110300&lon=126.96579&obs=ta,td,hm&itv=10&lat=37.57141&help=1"
weather_params = {"authKey": kma_auth_key}

weather_df = fetch_kma_data(weather_url, weather_params)
if weather_df is not None:
    display(weather_df.head())

"""### 5. 데이터 탐색 및 구조 확인 (EDA)
본격적인 모델링에 앞서, 주어진 데이터(산사태 이력 CSV, 산림청 TIF, 기상 데이터)의 실제 구조, 좌표계, 결측치 및 값 분포를 확인합니다.
"""

!pip install rasterio pyproj

import pandas as pd
import numpy as np
import rasterio
import os

print("=== 1. 산사태 발생 이력 CSV 데이터 확인 ===")
try:
    # 공공데이터 CSV는 보통 cp949 인코딩을 사용합니다.
    try:
        history_df = pd.read_csv(csv_path, encoding='cp949')
    except UnicodeDecodeError:
        history_df = pd.read_csv(csv_path, encoding='utf-8')

    print(f"데이터 크기: {history_df.shape}")
    print("\n[컬럼명 및 데이터 타입, 결측치 확인]")
    print(history_df.info())

    print("\n[데이터 미리보기]")
    display(history_df.head(3))
except Exception as e:
    print(f"CSV 파일 로드 오류: {e}")

print("=== 2. 산림청 산사태 위험지도 TIFF 데이터 확인 ===")
tif_paths = [tif1_path, tif3_path] # tif1(서울)과 tif3(강원) 사용

for path in tif_paths:
    print(f"\n[파일: {path}]")
    try:
        with rasterio.open(path) as src:
            print(f"좌표계 (CRS): {src.crs}")
            print(f"데이터 크기 (Width x Height): {src.width} x {src.height}")
            print(f"밴드 수: {src.count}")
            print(f"NoData 값: {src.nodata}")
            print(f"공간 범위 (Bounds): {src.bounds}")

            # 데이터 읽기 및 고유값 분포 확인
            band1 = src.read(1)
            unique_vals, counts = np.unique(band1, return_counts=True)
            print("[픽셀 값 분포]")
            for val, count in zip(unique_vals, counts):
                if val == 127 or val == src.nodata:
                    print(f"  값 {val} (NoData): {count} 픽셀")
                else:
                    print(f"  값 {val} (위험등급): {count} 픽셀")
    except Exception as e:
        print(f"TIFF 파일 로드 오류: {e}")

print("=== 3. 기상청 데이터 확인 ===")
if 'weather_df' in locals() and weather_df is not None:
    print(f"데이터 크기: {weather_df.shape}")
    print("\n[컬럼 및 결측치 정보]")
    print(weather_df.info())
    print(f"\n시작 시점: {weather_df['tm'].min()}")
    print(f"종료 시점: {weather_df['tm'].max()}")
else:
    print("weather_df가 현재 메모리에 없습니다. 이전 셀을 다시 실행해주세요.")

"""### 6. 주소 지오코딩 및 날짜 파싱 (Positive 샘플 전처리)
텍스트 주소를 위경도(EPSG:4326)로 변환하고, '재난구분' 컬럼에서 산사태 발생 시작일자를 추출합니다.
"""

from geopy.geocoders import Nominatim
import time
from tqdm import tqdm
import re
import numpy as np

# 1. 강원 지역만 필터링
target_df = history_df[history_df['상세주소_시도'].str.contains('강원', na=False)].copy()
print(f"강원도 지역 산사태 발생 데이터 수: {len(target_df)}건")

# 2. 발생 날짜 추출 함수 (예: '2021-07-05~07-08' -> '2021-07-05')
def extract_start_date(period_str):
    # YYYY-MM-DD 패턴 찾기
    match = re.search(r'\d{4}-\d{2}-\d{2}', str(period_str))
    if match:
        return match.group(0)
    return None

target_df['발생일자'] = target_df['재난구분'].apply(extract_start_date)

# 3. 전체 주소 텍스트 병합
target_df['상세주소_읍면도'] = target_df['상세주소_읍면도'].fillna('')
target_df['상세주소_리'] = target_df['상세주소_리'].fillna('')
target_df['전체주소'] = target_df['상세주소_시도'] + ' ' + target_df['상세주소_시군구'] + ' ' + target_df['상세주소_읍면도'] + ' ' + target_df['상세주소_리']
target_df['전체주소'] = target_df['전체주소'].str.strip()

# 4. 지오코딩 (Geopy Nominatim 사용)
geolocator = Nominatim(user_agent="landslide_predictor_agent")

lats = []
lons = []

print("지오코딩을 시작합니다... (데이터가 많아 시간이 꽤 소요될 수 있습니다!)")
for addr in tqdm(target_df['전체주소']):
    try:
        # 주소가 너무 상세하면 검색이 안될 수 있으므로, 리/동 단위까지만 사용
        search_addr = ' '.join(addr.split()[:3])
        location = geolocator.geocode(search_addr, timeout=10)
        if location:
            lats.append(location.latitude)
            lons.append(location.longitude)
        else:
            lats.append(np.nan)
            lons.append(np.nan)
        time.sleep(0.5) # API 호출 제한 방지
    except Exception as e:
        lats.append(np.nan)
        lons.append(np.nan)

target_df['latitude'] = lats
target_df['longitude'] = lons
target_df['landslide_occurred'] = 1 # Positive Label

# 위치를 찾지 못한 데이터는 제외
positive_df = target_df.dropna(subset=['latitude', 'longitude']).copy()
print(f"\n최종 확보된 Positive 샘플 수: {len(positive_df)}건")
display(positive_df[['발생일자', '전체주소', 'latitude', 'longitude']].head())

"""### 8. (해결) KDTree 기반 TIF 매핑 및 최종 공간 데이터셋 구성
도심지 반경 내에 산림이 없는 경우를 해결하기 위해, `cKDTree`를 활용하여 가장 가까운 유효 픽셀(1~5등급)을 찾아 매핑합니다.
"""

from scipy.spatial import cKDTree
from pyproj import Transformer
import random
import pandas as pd
import numpy as np
import rasterio
import datetime

positive_df_fixed = positive_df.copy()
positive_df_fixed = positive_df_fixed.dropna(subset=['발생일자']).copy()
# 데이터 누수 방지를 위한 고유 Group ID 부여
positive_df_fixed['group_id'] = range(len(positive_df_fixed))
print(f"지오코딩 및 날짜가 있는 초기 Positive 샘플 수: {len(positive_df_fixed)}건")

print("=== Positive 샘플 유실 문제 해결 (복수 TIF 병합 cKDTree 기반 탐색) ===")
transformer = Transformer.from_crs("EPSG:4326", "EPSG:5181", always_xy=True)
inv_transformer = Transformer.from_crs("EPSG:5181", "EPSG:4326", always_xy=True)

all_valid_coords = []
all_valid_vals = []
tif_paths = [tif1_path, tif3_path]

DOWN_SAMPLE_STEP = 100
for path in tif_paths:
    print(f"{path} 유효 픽셀 추출 중...")
    with rasterio.open(path) as src:
        band_data = src.read(1)
        valid_mask = (band_data >= 1) & (band_data <= 5)
        valid_rows, valid_cols = np.where(valid_mask)
        valid_vals = band_data[valid_rows, valid_cols]
        valid_rows = valid_rows[::DOWN_SAMPLE_STEP]
        valid_cols = valid_cols[::DOWN_SAMPLE_STEP]
        valid_vals = valid_vals[::DOWN_SAMPLE_STEP]
        valid_xs, valid_ys = rasterio.transform.xy(src.transform, valid_rows, valid_cols)
        coords = np.column_stack((valid_xs, valid_ys))
        all_valid_coords.append(coords)
        all_valid_vals.append(valid_vals)

combined_coords = np.vstack(all_valid_coords)
combined_vals = np.concatenate(all_valid_vals)
tree = cKDTree(combined_coords)

def get_nearest_valid_tif(lon, lat):
    x, y = transformer.transform(lon, lat)
    dist, idx = tree.query([[x, y]], k=1)
    return combined_vals[idx[0]]

positive_df_fixed['landslide_map_value'] = positive_df_fixed.apply(lambda row: get_nearest_valid_tif(row['longitude'], row['latitude']), axis=1)

# Negative Sample 생성
num_pos = len(positive_df_fixed)
negative_samples_fixed = []
next_group_id = len(positive_df_fixed)

# 1. Temporal Negative (동일 위치, 다른 날짜 -> 동일 Group ID)
for _, row in positive_df_fixed.iterrows():
    orig_date = datetime.datetime.strptime(row['발생일자'], '%Y-%m-%d')
    random_days_ago = random.randint(100, 400)
    new_date = orig_date - datetime.timedelta(days=random_days_ago)
    negative_samples_fixed.append({
        'latitude': row['latitude'], 'longitude': row['longitude'],
        'landslide_map_value': row['landslide_map_value'],
        'landslide_occurred': 0, '발생일자': new_date.strftime('%Y-%m-%d'),
        'group_id': row['group_id']
    })

# 2. Spatial Negative (랜덤 위치 -> 새로운 Group ID)
target_spatial_neg = num_pos * 2
random_indices = np.random.choice(len(combined_vals), size=target_spatial_neg, replace=False)
for idx in random_indices:
    val = combined_vals[idx]
    x, y = combined_coords[idx]
    lon, lat = inv_transformer.transform(x, y)
    negative_samples_fixed.append({
        'latitude': lat, 'longitude': lon, 'landslide_map_value': val,
        'landslide_occurred': 0,
        '발생일자': random.choice(positive_df_fixed['발생일자'].tolist()) if num_pos > 0 else '2022-08-08',
        'group_id': next_group_id
    })
    next_group_id += 1

negative_df_fixed = pd.DataFrame(negative_samples_fixed)
final_df = pd.concat([positive_df_fixed[['latitude', 'longitude', '발생일자', 'landslide_map_value', 'landslide_occurred', 'group_id']], negative_df_fixed], ignore_index=True)

print("\n=== 최종 라벨(Y) 분포 ===")
print(final_df['landslide_occurred'].value_counts())
display(final_df.head())

"""### 9. 기상 및 지형 파생 Feature 생성 파이프라인
산사태 발생일자를 기준으로 이전 기상 데이터(누적 강수량 등)와 지형 데이터(경사도, 고도 등)를 구축합니다.
"""

import datetime
import time
import requests
from tqdm import tqdm
import numpy as np
import pandas as pd
import rasterio
import math
from pyproj import Transformer

tqdm.pandas(desc="기상/지형 데이터 API 및 파일 추출 중")

def get_real_weather_features(date_str, lat, lon):
    try:
        target_date = datetime.datetime.strptime(date_str, '%Y-%m-%d')
        start_date = (target_date - datetime.timedelta(days=3)).strftime('%Y-%m-%d')

        url = f"https://archive-api.open-meteo.com/v1/archive?latitude={lat}&longitude={lon}&start_date={start_date}&end_date={date_str}&hourly=precipitation&timezone=Asia%2FSeoul"
        response = requests.get(url, timeout=10)
        data = response.json()

        if 'hourly' in data and 'precipitation' in data['hourly']:
            # API 응답 전체 시계열 강수량
            rain_values = [v if v is not None else 0.0 for v in data['hourly']['precipitation']]
            s = pd.Series(rain_values)

            # 해당 산사태 발생일(마지막 24시간) 기준 누적 연산
            # 배열의 마지막 24개가 발생일 당일의 데이터임
            s_target = s.iloc[-24:].reset_index(drop=True)
            s_48h = s.iloc[-48:].reset_index(drop=True)
            s_72h = s.iloc[-72:].reset_index(drop=True)

            rain_1h = s_target.iloc[-1] if len(s_target) > 0 else 0.0 # 직전 1시간
            rain_3h = s_target.rolling(window=3, min_periods=1).sum().max()
            rain_6h = s_target.rolling(window=6, min_periods=1).sum().max()
            rain_12h = s_target.rolling(window=12, min_periods=1).sum().max()
            rain_24h = s_target.sum()
            rain_48h = s_48h.sum()
            rain_72h = s_72h.sum()

            return rain_1h, rain_3h, rain_6h, rain_12h, rain_24h, rain_48h, rain_72h
        else:
            return 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
    except Exception as e:
        return 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

def get_terrain_from_dem(lat, lon, dem_src, transformer_dem):
    try:
        x, y = transformer_dem.transform(lon, lat)
        row, col = dem_src.index(x, y)
        window = dem_src.read(1, window=rasterio.windows.Window(col-1, row-1, 3, 3))
        elevation = window[1, 1]
        if elevation == dem_src.nodata or np.isnan(elevation):
            return 0.0, 0.0
        res_x, res_y = dem_src.res
        if window.shape == (3, 3):
            a, b, c = window[0, 0], window[0, 1], window[0, 2]
            d, e, f = window[1, 0], window[1, 1], window[1, 2]
            g, h, i = window[2, 0], window[2, 1], window[2, 2]
            dz_dx = ((c + 2*f + i) - (a + 2*d + g)) / (8 * res_x)
            dz_dy = ((g + 2*h + i) - (a + 2*b + c)) / (8 * res_y)
            slope_percent = math.sqrt(dz_dx**2 + dz_dy**2)
            slope_deg = math.atan(slope_percent) * (180 / math.pi)
        else:
            slope_deg = 0.0
        return float(slope_deg), float(elevation)
    except Exception:
        return 0.0, 0.0

def generate_features_pipeline(df):
    print("데이터 추출 준비 중...")
    try:
        dem_src = rasterio.open(dem_path)
        dem_crs = dem_src.crs if dem_src.crs else "EPSG:5179"
        transformer_dem = Transformer.from_crs("EPSG:4326", dem_crs, always_xy=True)
    except Exception as e:
        dem_src = None
        transformer_dem = None

    def apply_features(row):
        time.sleep(0.05)
        rain_1h, rain_3h, rain_6h, rain_12h, rain_24h, rain_48h, rain_72h = get_real_weather_features(row['발생일자'], row['latitude'], row['longitude'])
        if dem_src is not None:
            slope, elevation = get_terrain_from_dem(row['latitude'], row['longitude'], dem_src, transformer_dem)
        else:
            slope, elevation = 0.0, 0.0
        return pd.Series({
            'rain_1h': rain_1h, 'rain_3h': rain_3h, 'rain_6h': rain_6h,
            'rain_12h': rain_12h, 'rain_24h': rain_24h, 'rain_48h': rain_48h, 'rain_72h': rain_72h,
            'slope': slope, 'elevation': elevation
        })

    features = df.progress_apply(apply_features, axis=1)
    if dem_src: dem_src.close()
    return pd.concat([df, features], axis=1)

ml_df = generate_features_pipeline(final_df)
print("\n=== 학습용 최종 데이터셋(ml_df) 미리보기 ===")
display(ml_df.head())

"""### 과거 날짜 기상청 API 응답 원본 확인
과거 일자(2022-07-12)로 실시간 API 엔드포인트(`sfc_nc_var.php`)를 호출했을 때, 실제로 어떤 형태의 데이터가 반환되는지 확인합니다.
"""

import requests

# 이전 단계 디버그에서 확인된 KMA API URL
debug_url = "https://apihub.kma.go.kr/api/typ01/url/sfc_nc_var.php?tm1=202207120000&tm2=202207132350&lon=127.8402504&lat=37.8866454&obs=rn&itv=60&help=1&authKey="

print("API 요청 전송 중...")
response = requests.get(debug_url)

print("\n=== 기상청 API 과거 데이터 요청 원본 응답 ===")
# 데이터가 너무 길 수 있으므로 20줄 정도만 출력합니다.
lines = response.text.split('\n')
for line in lines[:20]:
    print(line)

"""### 10. Random Forest 모델 학습 및 성능 평가
전처리가 완료된 데이터를 바탕으로 Train/Test 셋을 분리하고, 모델을 학습한 뒤 각종 평가 지표를 출력합니다.
"""

from sklearn.model_selection import GroupShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

rain_cols = ['rain_1h', 'rain_3h', 'rain_6h', 'rain_12h', 'rain_24h', 'rain_48h', 'rain_72h']
terrain_cols = ['slope', 'elevation']
map_cols = ['landslide_map_value']
all_cols = rain_cols + terrain_cols + map_cols

print("\n================ 1. 데이터 검증 ================")
print(f"전체 샘플 수: {len(ml_df)} | Positive: {sum(ml_df['landslide_occurred']==1)} | Negative: {sum(ml_df['landslide_occurred']==0)}")
print("\n[피처 전체 통계량]")
display(ml_df[all_cols].describe())

print("\n[강수량 0값 및 Unique 분석]")
for col in rain_cols:
    zeros = (ml_df[col] == 0).sum()
    uniques = ml_df[col].nunique()
    print(f"{col}: 0값 {zeros}개, 고유값 {uniques}개")

print("\n[강수량 > 0 인 샘플 미리보기 (데이터 존재 여부 확인)]")
rain_exists = ml_df[ml_df['rain_72h'] > 0]
if len(rain_exists) > 0:
    display(rain_exists[['발생일자', 'landslide_occurred'] + rain_cols].head())
else:
    print("경고: 강수량 데이터가 모두 0입니다! API 호출 결과를 다시 확인해야 합니다.")

print("\n================ 2. 모델별 학습 및 비교 ================")
# 데이터 누수 방지를 위한 Group 분할 (동일 위치/사건이 분리되지 않도록)
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(ml_df, ml_df['landslide_occurred'], groups=ml_df['group_id']))

train_df, test_df = ml_df.iloc[train_idx], ml_df.iloc[test_idx]
y_train, y_test = train_df['landslide_occurred'], test_df['landslide_occurred']

feature_sets = {
    "A. 강수량만 (Rain Only)": rain_cols,
    "B. 지형만 (Terrain Only)": terrain_cols,
    "C. 위험지도만 (Map Only)": map_cols,
    "D. 전체 피처 (All Features)": all_cols
}

for name, cols in feature_sets.items():
    print(f"\n>>> 모델 시나리오: {name}")
    X_train, X_test = train_df[cols], test_df[cols]

    pipe = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('rf', RandomForestClassifier(n_estimators=100, max_depth=10, class_weight='balanced', random_state=42))
    ])

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    y_proba = pipe.predict_proba(X_test)[:, 1]

    cm = confusion_matrix(y_test, y_pred)
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f} | Precision: {precision_score(y_test, y_pred, zero_division=0):.4f} | Recall: {recall_score(y_test, y_pred, zero_division=0):.4f} | F1: {f1_score(y_test, y_pred, zero_division=0):.4f} | ROC-AUC: {roc_auc_score(y_test, y_proba):.4f}")
    print(f"Confusion Matrix:\nTN={cm[0][0]} FP={cm[0][1]}\nFN={cm[1][0]} TP={cm[1][1]}")

    if len(cols) > 1:
        importances = pipe.named_steps['rf'].feature_importances_
        imp_df = pd.DataFrame({'Feature': cols, 'Importance': importances}).sort_values(by='Importance', ascending=False)
        print("Feature Importances:")
        for _, row in imp_df.iterrows():
            print(f"  - {row['Feature']}: {row['Importance']:.4f}")

"""### 10-1. 모델 성능 및 데이터 상관관계 시각화
피처 간의 상관관계, Confusion Matrix, ROC Curve, 그리고 Feature Importance를 시각적으로 확인합니다.
"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, auc, ConfusionMatrixDisplay

# 시각화 스타일 설정
sns.set_theme(style="whitegrid")
plt.style.use('default')

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1. Feature Correlation Matrix (상관관계 히트맵)
# 산사태 발생(landslide_occurred)과 각 피처들의 상관관계를 확인합니다.
corr = ml_df[all_cols + ['landslide_occurred']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", ax=axes[0, 0])
axes[0, 0].set_title('Feature Correlation Matrix', fontsize=14)

# 2. Confusion Matrix (오차 행렬)
cm_display = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No Landslide (0)', 'Landslide (1)'])
cm_display.plot(ax=axes[0, 1], cmap='Blues', colorbar=False)
axes[0, 1].set_title('Confusion Matrix', fontsize=14)
axes[0, 1].grid(False) # 오차 행렬 배경 그리드 제거

# 3. ROC Curve (수신자 조작 특성 곡선)
fpr, tpr, thresholds = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)
axes[1, 0].plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
axes[1, 0].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
axes[1, 0].set_xlim([0.0, 1.0])
axes[1, 0].set_ylim([0.0, 1.05])
axes[1, 0].set_xlabel('False Positive Rate')
axes[1, 0].set_ylabel('True Positive Rate')
axes[1, 0].set_title('Receiver Operating Characteristic (ROC)', fontsize=14)
axes[1, 0].legend(loc="lower right")

# 4. Feature Importance (피처 중요도)
sns.barplot(x='Importance', y='Feature', data=imp_df, ax=axes[1, 1], palette='viridis', hue='Feature', legend=False)
axes[1, 1].set_title('Feature Importance', fontsize=14)
axes[1, 1].set_xlabel('Importance Score')
axes[1, 1].set_ylabel('Features')

# 전체 레이아웃 조정 및 출력
plt.tight_layout()
plt.show()

"""### 11. 최종 모델 및 데이터 저장
FastAPI 서버에서 사용할 수 있도록 Pipeline 형태의 모델과 최종 전처리된 CSV 데이터를 저장합니다.
"""

# 1. 파이프라인 모델 저장
model_save_path = "landslide_pipeline.joblib"
joblib.dump(pipe, model_save_path)
print(f"모델이 성공적으로 저장되었습니다: {model_save_path}")

# 2. 최종 학습 데이터 CSV 저장
csv_save_path = "landslide_training_data.csv"
ml_df.to_csv(csv_save_path, index=False, encoding='utf-8-sig')
print(f"최종 학습 데이터셋이 저장되었습니다: {csv_save_path}")

# 3. 백엔드(FastAPI) 개발자를 위한 Feature 스키마 안내
print("\n[FastAPI 백엔드 예측 API 구성 안내]")
print(f"predict_proba()를 호출하기 위해서는 다음 {len(all_cols)}개의 Feature가 순서대로 배열 또는 DF로 입력되어야 합니다:")
for idx, f in enumerate(all_cols, 1):
    print(f"  {idx}. {f}")